name: Unit tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true
        id: go

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install
          bc
          gcc
          libgl1-mesa-dev
          libwayland-dev
          libx11-dev
          libxkbcommon-dev
          xorg-dev
          xvfb
        if: ${{ runner.os == 'Linux' }}

      - name: gofmt
        run: make gofmt

      - name: govet
        run: make govet

      - name: go mod verify
        run: go mod verify

      - name: Test
        run: |
            go install gotest.tools/gotestsum@latest
            make test

      - name: Linting
        run: |
            go install honnef.co/go/tools/cmd/staticcheck@latest
            staticcheck ./...

      - name: govulncheck
        run: |
            go install golang.org/x/vuln/cmd/govulncheck@latest
            govulncheck ./...

      - name: Build
        run: make build

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
